name: Build and Deploy PRO
on:
  push:
    tags:
      - '/^v[0-9.]+$/'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Install and Build
        run: |
          pnpm install
          pnpm run build:sit
      - name: Log in to Docker Hub # 登陆腾讯云docker 镜像仓库
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract tag name # 导出提取tag标签
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})" # 提取tag
        id: extract_tag

      - name: Docker Build and push # Docker 的构建和推送远程的腾讯云仓库
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ccr.ccs.tencentyun.com/huangwentao/chat-frontend:${{ steps.extract_tag.outputs.tag }}

      # - name: ssh docker login # 登陆云服务器
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: cd ~ && sh deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} # 运行脚本
      #     host: ${{ secrets.TENCENT_CLOUD_IP }} # 云服务器的ip
      #     username: ${{ secrets.TENCENT_CLOUD_NAME }} # 云服务器的用户名
      #     password: ${{ secrets.TENCENT_CLOUD_PASSWORD }} # 云服务器的密码
